### ISSUE TITLE
Missing header file

### ISSUE THREAD

**Issue by rfortunatov** [espressif/esp-zboss-lib#2]
Header file zboss_api_mm.h included in zboss_api_nwk.h is missing from repository which prevent compilation

**Comment by xieqinan** [comment]
Hi rfortunatov,

I regret to hear about your failure. I would like to know more detailed information to confirm this problem.

Firstly, could you please specify which example from the ESP repository is experiencing this problem?

Secondly, have you tried using the `sp-zigbee-sdk` to develop your application?

Thirdly, does the file `zboss_api.h` include what you need in your example?

**Comment by rfortunatov** [comment]
Hi @xieqinan 
1 - I'm actually not trying to build an example from esp-idf, but rather trying to build my own zigbee enabled application on top of zboss-lib.
2 - I've tried using the sdk, though folks from development team are taking a pretty long time to add new clusters to the sdk and I need some extended list of clusters for my project. Therefore I've decided to try and develop something myself. 
3 - Yep, that's one of includes I need for my project. The specific issue is that that one requires zboss_api_nwk.h, and zboss_api_nwk.h requires zboss_api_mm.h which evidently contains ZB_NWK_MAC_IFACE_TBL_SIZE define.

As of now I've just commented out that include in zboss_api_nwk.h and used an arbitrary value for ZB_NWK_MAC_IFACE_TBL_SIZE to get things built. Though I doubt that it's a correct way to handle things :)

**Comment by Ravenen** [comment]
I encounter the same issue when trying to use `ZB_AF_SET_ENDPOINT_HANDLER`.  
The goal remains unchanged: the `esp-zigbee-sdk` doesn't have enough APIs yet as it's still in development. So, I wanted to experiment with some functionalities before they are implemented in the SDK.

**Comment by rfortunatov** [comment]
@Ravenen  If you're not tight to Zigbee specifically for some reason and just into an IoT development you could give matter a go. It's still in development too, but at least they're open source and you can contribute and change whatever you want.

**Comment by Ravenen** [comment]
@rfortunatov Thank you so much for the advice. I truly appreciate it. Yes, Matter can fulfill my requirements, but unfortunately, I specifically require ZigBee, so that's not an option for me.  
By the way, I also partially resolved my issue by copying the `typedef`s that are needed directly from the `zboss_api_nwk.h` file so that the 'include' is not required. However, this is just a workaround, and it doesn't appear to be a proper solution.

**Comment by chshu** [comment]
Please build the application on top of esp-zigbee-lib APIs: https://github.com/espressif/esp-zigbee-sdk/tree/main/components/esp-zigbee-lib/include. Please file github issue for anything missing in [esp-zigbee-sdk](https://github.com/espressif/esp-zigbee-sdk).
