### ISSUE TITLE
[REQUEST] Zigbee NCP (Network Co-Processor) mode support? (TZ-374)

### ISSUE THREAD

**Issue by Hedda** [espressif/esp-zboss-lib#4]
This feature request is also related to https://github.com/espressif/esp-zigbee-sdk/issues/124

> The current release only has ZBOSS RCP, but our old implementation uses ZBOSS NCP host.
> 
> The ZBOSS libraries for the NCP host include the following stack layers:
> 
> ```
> Zigbee cluster library (ZCL)
> Commissioning logic (part of ZDO)
> ZBOSS NCP serialization protocol
> ZBOSS platform support layer for Linux-based OS
> ```
> 
> Since you use ZBOSS already if it is possible that we can use our old implementation with ZBOSS NCP host or if we need to rewrite it against esp-zigbee-sdk. It would be enough for us if we could get the ZBOSS NCP SoC firmware files.

Can you please consider adding support for ZBOSS NCP host for Zigbee NCP (Network Co-Processor) mode?

Currently is seems like esp-zboss-lib only support Zigbee via a RCP (Radio Co-Processor) mode and no support for ZBOSS NCP host?

See example:

https://developer.nordicsemi.com/nRF_Connect_SDK/doc/zboss/3.11.2.0/zboss_ncp_host_intro.html

https://developer.nordicsemi.com/nRF_Connect_SDK/doc/zboss/3.11.2.0/zboss_ncp_host.html

ZBOSS NCP host as Zigbee NCP mode is required to implement support in the zigpy-zboss radio library for zigpy as a Zigbee Coordinator adapter interface which is used by the ”ZHA” Zigbee gateway integration that is built-into Home Assistant:

https://github.com/kardia-as/zigpy-zboss/issues/19

https://github.com/kardia-as/zigpy-zboss

https://github.com/zigpy/zigpy

https://www.home-assistant.io/integrations/zha

**Comment by Hedda** [comment]
ZBOSS NCP support would probably also be prefered for [Zigbee2Tasmota (Z2T)](https://tasmota.github.io/docs/Zigbee/) compatible in Tasmota:

https://github.com/arendst/Tasmota/discussions/20045

For reference, Tasmotas's Zigbee2Tasmota (Z2T) already supports Texas Instruments ZNP and Silicon Labs EZSP Zigbee stacks/interfaces with respective Zigbee Coordinator adapter running Zigbee firmware in NCP (Network Co-Processor) mode:

https://tasmota.github.io/docs/Zigbee/

**Comment by chshu** [comment]
Will follow up in https://github.com/espressif/esp-zigbee-sdk/issues/124#issuecomment-1833291850
