### ISSUE TITLE
Duplicate #ifdef in Device Config (TZ-579)

### ISSUE THREAD

**Issue by wipmate** [espressif/esp-zboss-lib#5]
It appears as if [line 386 in zb_ha_device_config.h](https://github.com/espressif/esp-zboss-lib/blob/f0e12dc1bf5b61110721f8e3cdbd0b697e486397/include/ha/zb_ha_device_config.h#L386) is meant to say `#ifdef ZB_HA_DEFINE_DEVICE_DIMMER_SWITCH` instead of `#ifdef ZB_HA_DEFINE_DEVICE_DIMMABLE_LIGHT`. (Otherwise there would be conflicting defines.)

**Comment by xieqinan** [comment]
@wipmate ，

Thanks for your suggestion, we will fixed it in next release.

**Comment by chshu** [comment]
Fixed in https://github.com/espressif/esp-zboss-lib/commit/66912eadab2e3393abca10a496a34d4bf18d731f.
